Repository LunaPg/eorzea-alarm-fishing, pull requests merged in 2022-10, with the labels that each got.

#2 feat(config): add eslint, prettier, package.json and index.ts
  .eslintrc
  .prettierrc
  package-lock.json
  package.json
  src/index.ts
Labels: enhancement, hacktoberfest

#3 Feat/GitHub template pr
  .github/PULL_REQUEST_TEMPLATE/pr-template.md
  package.json
Labels: documentation, enhancement, hacktoberfest

#7 fix(jest): ts jest config + gitignore on lib
  jest.config.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#9 Move & rename PR template
  .github/pull_request_template.md
Labels: hacktoberfest, hacktoberfest-accepted
